/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        'surface': '#f7f9fb',
        'surface-dim': '#d8dadc',
        'surface-bright': '#f7f9fb',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f2f4f6',
        'surface-container': '#eceef0',
        'surface-container-high': '#e6e8ea',
        'surface-container-highest': '#e0e3e5',
        'on-surface': '#191c1e',
        'on-surface-variant': '#45464d',
        'inverse-surface': '#2d3133',
        'inverse-on-surface': '#eff1f3',
        'outline': '#76777d',
        'outline-variant': '#c6c6cd',
        'surface-tint': '#565e74',
        'primary': '#0F172A',
        'on-primary': '#ffffff',
        'primary-container': '#131b2e',
        'on-primary-container': '#7c839b',
        'inverse-primary': '#bec6e0',
        'secondary': '#334155',
        'on-secondary': '#ffffff',
        'secondary-container': '#d5e3fd',
        'on-secondary-container': '#57657b',
        'tertiary': '#10B981',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#002113',
        'on-tertiary-container': '#009668',
        'error': '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'background': '#F8FAFC',
        'on-background': '#191c1e',
        'surface-variant': '#e0e3e5',
        'booked-emerald': '#10B981',
        'pending-amber': '#F59E0B',
        'matched-blue': '#3B82F6',
        'border-subtle': '#E2E8F0',
        'text-muted': '#64748B',
      },
      fontFamily: {
        'sans': ['Inter', 'sans-serif'],
        'heading': ['Geist', 'sans-serif'],
        'mono': ['JetBrains Mono', 'monospace'],
      },
      borderRadius: {
        'sm': '0.125rem',
        DEFAULT: '0.25rem',
        'md': '0.375rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
        'full': '9999px',
      },
      spacing: {
        'base': '4px',
        'container-margin': '24px',
        'gutter': '16px',
        'stack-sm': '8px',
        'stack-md': '16px',
        'stack-lg': '32px',
      }
    },
  },
  plugins: [],
}
