const db = require('../../config/db');
const Groq = require('groq-sdk');
const groq = new Groq({ apiKey: process.env.GROQ_API_KEY });

async function getRecommendationsForRequirement(requirementId) {
  const reqRes = await db.query(
    `SELECT r.*, u.name as user_name, p.tags as user_tags 
     FROM requirements r 
     JOIN users u ON r.user_id = u.id 
     LEFT JOIN user_profiles p ON u.id = p.user_id 
     WHERE r.id = $1`, [requirementId]
  );
  
  if (reqRes.rows.length === 0) return [];
  const requirement = reqRes.rows[0];

  let tagFilter = '';
  if (requirement.call_type === 'resume_revamp') tagFilter = 'Big company';
  if (requirement.call_type === 'job_market_guidance') tagFilter = 'Good communication';
  if (requirement.call_type === 'mock_interview') {
    const uTags = requirement.user_tags || [];
    if (uTags.includes('Tech')) tagFilter = 'Tech';
    if (uTags.includes('Non-tech')) tagFilter = 'Non-tech';
  }

  let candidateQuery = `
    SELECT u.id, u.name, p.tags, p.description, p.rating_avg, p.rating_count 
    FROM users u 
    JOIN mentor_profiles p ON u.id = p.user_id 
    WHERE u.role = 'mentor' AND p.is_active = true
  `;
  const candidateRes = await db.query(candidateQuery);
  let candidates = candidateRes.rows;

  if (tagFilter) {
    const strictFilter = candidates.filter(c => (c.tags || []).includes(tagFilter));
    if (strictFilter.length > 0) {
      candidates = strictFilter;
    }
  }

  if (candidates.length === 0) return [];

  const prompt = `
    You are an expert matchmaking assistant. Rank the following mentor candidates for a user's requirement.
    
    User Requirement:
    Call Type: ${requirement.call_type}
    Description: ${requirement.description}
    Tags: ${(requirement.user_tags || []).join(', ')}
    
    Candidates:
    ${candidates.map(c => `ID: ${c.id}, Name: ${c.name}, Tags: ${(c.tags || []).join(', ')}, Description: ${c.description}`).join('\n\n')}
    
    Output JSON in this format:
    {
      "matches": [
        { "mentor_id": "...", "fit_score": 95, "rationale": "Strong fit..." }
      ]
    }
    Sort by fit_score descending. Provide a 1-2 sentence rationale per mentor. Keep it concise.
  `;

  let ranked = [];
  try {
    const chatCompletion = await groq.chat.completions.create({
      messages: [{ role: "user", content: prompt }],
      model: "llama-3.1-8b-instant",
      response_format: { type: "json_object" },
    });

    const text = chatCompletion.choices[0]?.message?.content || '{"matches": []}';
    const parsed = JSON.parse(text);
    ranked = parsed.matches || [];
  } catch (e) {
    console.error("LLM Ranking failed", e);
    ranked = candidates.map((c, idx) => ({ 
      mentor_id: c.id, 
      fit_score: Math.max(10, 85 - (idx * 5)), 
      rationale: "Match generated by fallback engine." 
    }));
  }

  const finalMatches = [];
  for (const r of ranked) {
    const mentor = candidates.find(c => c.id === r.mentor_id);
    if (mentor) {
      finalMatches.push({
        ...mentor,
        fit_score: r.fit_score,
        rationale: r.rationale
      });
    }
  }

  return finalMatches;
}

module.exports = { getRecommendationsForRequirement };
